package tenantisolation

import (
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
	"time"
)

const fixtureModulePath = "github.com/ankek/Household-Objects-Dev/server"

const fixtureTemplate = `// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by tests/tenant_isolation/compilefail_test.go. DO NOT EDIT.

package fixture

import (
	"context"
	"net/http"

	"github.com/ankek/Household-Objects-Dev/server/internal/httpapi/middleware"
	"github.com/ankek/Household-Objects-Dev/server/internal/storage"
%s)

func sanctioned(ctx context.Context, st *storage.Storage) {
	groupID, err := storage.NewGroupID("g1")
	if err != nil {
		panic(err)
	}
	scope, err := st.ForGroup(groupID)
	if err != nil {
		panic(err)
	}
	if _, err := scope.Items().Get(ctx, "item-1"); err != nil {
		panic(err)
	}
	if _, err := scope.Items().List(ctx, storage.Page{Limit: 1}); err != nil {
		panic(err)
	}
	if scope.GroupID().IsZero() {
		panic("unreachable")
	}

	var scoped middleware.ScopedHandler = func(w http.ResponseWriter, r *http.Request, s storage.Scope) {
		_, _ = s.Items().List(r.Context(), storage.Page{Limit: 1})
	}
	http.HandleFunc("/items", middleware.Scoped(scoped))

%s}
`

type compileVerdict int

const (
	verdictCompiled compileVerdict = iota
	verdictExpected
	verdictWrongReason
)

func (v compileVerdict) String() string {
	switch v {
	case verdictCompiled:
		return "verdictCompiled"
	case verdictExpected:
		return "verdictExpected"
	case verdictWrongReason:
		return "verdictWrongReason"
	default:
		return fmt.Sprintf("compileVerdict(%d)", int(v))
	}
}

type fixtureCase struct {
	name    string
	claim   string
	imports string
	body    string
	want    *regexp.Regexp
}

func storageConstructionCases() []fixtureCase {
	return []fixtureCase{
		{
			name:  "groupid_conversion",
			claim: "GroupID is a struct, not a defined string type, precisely so that a conversion from an arbitrary string -- a user id, a path segment, \"\" -- is not an expression that exists outside internal/storage",
			body:  "\t_ = storage.GroupID(\"g1\")\n",
			want:  regexp.MustCompile(`cannot convert "g1" \(untyped string constant\) to type storage\.GroupID`),
		},
		{
			name:  "groupid_composite_literal",
			claim: "GroupID's field is unexported so that a composite literal cannot mint a scope that skipped NewGroupID's validation",
			body:  "\t_ = storage.GroupID{id: \"g1\"}\n",
			want:  regexp.MustCompile(`unexported field id in struct literal`),
		},
		{
			name:  "scope_composite_literal",
			claim: "Scope is an interface over an unexported implementation so that there is no exported struct whose empty literal would be a scope bound to no group",
			body:  "\t_ = storage.Scope{}\n",
			want:  regexp.MustCompile(`invalid composite literal type storage\.Scope`),
		},
		{
			name:  "item_repository_composite_literal",
			claim: "ItemRepository is an interface for the same reason Scope is: a repository literal would be one bound to no group, and its queries would bind their predicate to the empty string",
			body:  "\t_ = storage.ItemRepository{}\n",
			want:  regexp.MustCompile(`invalid composite literal type storage\.ItemRepository`),
		},
		{
			name:  "groupscope_is_unnameable",
			claim: "the only implementation of Scope that can reach the database is unexported, so it cannot be named, embedded or constructed above this layer",
			body:  "\t_ = storage.groupScope{}\n",
			want:  regexp.MustCompile(`undefined: storage\.groupScope`),
		},
		{
			name:  "group_is_not_a_call_site_parameter",
			claim: "no repository method takes a group: the scope is a property of the value the caller was handed, not an argument it could pass wrongly or forget",
			body:  "\t_, _ = scope.Items().Get(ctx, groupID, \"item-1\")\n",
			want:  regexp.MustCompile(`too many arguments`),
		},
		{
			name:    "generated_sql_is_unreachable",
			claim:   "the generated query set lives under internal/storage/internal/gen so that Go's internal rule -- not a reviewer -- keeps SQL out of every package above internal/storage",
			imports: "\n\t\"" + fixtureModulePath + "/internal/storage/internal/gen\"\n",
			body:    "\tvar _ *gen.Queries\n",
			want:    regexp.MustCompile(`use of internal package .*internal/storage/internal/gen not allowed`),
		},
		{
			name:    "connection_pools_are_unreachable",
			claim:   "the pools live under internal/storage/internal/db for the same reason: a caller holding a *sql.DB can hand-write a statement with no group predicate and nothing below would see it",
			imports: "\n\t\"" + fixtureModulePath + "/internal/storage/internal/db\"\n",
			body:    "\tvar _ *db.Store\n",
			want:    regexp.MustCompile(`use of internal package .*internal/storage/internal/db not allowed`),
		},
	}
}

func middlewareSurfaceCases() []fixtureCase {
	return []fixtureCase{
		{
			name:  "no_scope_from_context",
			claim: "there is no exported FromContext for the scope: its signature would be (Scope, bool), and a handler that ignores the bool proceeds with a nil scope -- which is the unscoped handler NFR-011 abolishes, reintroduced through the context",
			body:  "\t_, _ = middleware.ScopeFromContext(ctx)\n",
			want:  regexp.MustCompile(`undefined: middleware\.ScopeFromContext`),
		},
		{
			name:  "no_must_scope",
			claim: "nor the panicking variant of the same accessor",
			body:  "\t_ = middleware.MustScope(ctx)\n",
			want:  regexp.MustCompile(`undefined: middleware\.MustScope`),
		},
		{
			name:  "scoped_handler_is_not_an_http_handlerfunc",
			claim: "a ScopedHandler cannot be registered as a bare handler: mounting it has to go through Scoped, which is what puts the 500-on-mis-mounted-route check in front of every scoped route",
			body:  "\tvar _ http.HandlerFunc = scoped\n",
			want:  regexp.MustCompile(`cannot use scoped \(variable of (func )?type middleware\.ScopedHandler\) as http\.HandlerFunc value`),
		},
		{
			name:  "scoped_handler_is_not_an_http_handler",
			claim: "and cannot be mounted on a router either -- it satisfies no handler interface",
			body:  "\thttp.Handle(\"/items\", scoped)\n",
			want:  regexp.MustCompile(`does not implement http\.Handler`),
		},
	}
}

func TestUnscopedConstructionDoesNotCompile(t *testing.T) {
	goBin := requireGoToolchain(t)

	cases := append(storageConstructionCases(), middlewareSurfaceCases()...)
	if len(cases) < 12 {
		t.Fatalf("only %d compile-fail cases; the table has lost claims and this test no longer covers P-3", len(cases))
	}

	root := fixtureRoot(t)

	controlDir, controlSrc := writeFixture(t, root, "control", "", "")
	if out, err := buildFixture(t, goBin, controlDir); err != nil {
		t.Fatalf("the positive control does not compile, so this harness proves nothing and every negative case below would 'pass' for the wrong reason.\ngo build: %v\n%s\n--- fixture ---\n%s", err, out, controlSrc)
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			dir, src := writeFixture(t, root, tc.name, tc.imports, tc.body)
			verdict, out := classifyFixture(t, goBin, dir, tc.want)

			switch verdict {
			case verdictCompiled:
				t.Errorf("this compiles, so the claim does not hold: %s\n--- fixture ---\n%s", tc.claim, src)
			case verdictWrongReason:
				t.Errorf("the fixture failed to build, but not with %q -- so it proves nothing about the claim, and the harness is what needs fixing, not the code under test.\n--- go build ---\n%s\n--- fixture ---\n%s", tc.want, out, src)
			case verdictExpected:
			}
		})
	}
}

func TestCompileFailHarnessDistinguishesItsOutcomes(t *testing.T) {
	goBin := requireGoToolchain(t)
	root := fixtureRoot(t)

	dir, _ := writeFixture(t, root, "selftest_hole_is_real", "", "\t_ = storage.MustGroupID(\"g1\")\n")
	if verdict, out := classifyFixture(t, goBin, dir, regexp.MustCompile(`cannot convert`)); verdict != verdictCompiled {
		t.Errorf("a fixture that compiles was classified %v, want verdictCompiled; the harness would report a real hole as a proven claim\n%s", verdict, out)
	}

	dir, _ = writeFixture(t, root, "selftest_wrong_reason", "", "\t_ = storage.NoSuchSymbolInThisPackage{}\n")
	if verdict, out := classifyFixture(t, goBin, dir, regexp.MustCompile(`cannot convert "g1" \(untyped string constant\)`)); verdict != verdictWrongReason {
		t.Errorf("a fixture that failed for an unrelated reason was classified %v, want verdictWrongReason; the harness would accept a typo as proof\n%s", verdict, out)
	}
}

func requireGoToolchain(t *testing.T) string {
	t.Helper()
	goBin, err := exec.LookPath("go")
	if err != nil {
		t.Skipf("no go toolchain on PATH, so the compile-time half of P-3 cannot be checked here: %v", err)
	}
	return goBin
}

func fixtureRoot(t *testing.T) string {
	t.Helper()
	root := filepath.Join("testdata", "nocompile")
	if err := os.RemoveAll(root); err != nil {
		t.Fatalf("clear %s: %v", root, err)
	}
	t.Cleanup(func() {
		_ = os.RemoveAll(root)
		_ = os.Remove(filepath.Dir(root))
	})
	return root
}

func writeFixture(t *testing.T, root, name, imports, body string) (dir, src string) {
	t.Helper()
	dir = filepath.Join(root, name)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatalf("create fixture dir %s: %v", dir, err)
	}
	src = fmt.Sprintf(fixtureTemplate, imports, body)
	if err := os.WriteFile(filepath.Join(dir, "fixture.go"), []byte(src), 0o644); err != nil {
		t.Fatalf("write fixture %s: %v", dir, err)
	}
	return dir, src
}

func buildFixture(t *testing.T, goBin, dir string) (string, error) {
	t.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()

	cmd := exec.CommandContext(ctx, goBin, "build", "./"+filepath.ToSlash(dir))
	out, err := cmd.CombinedOutput()
	if ctx.Err() != nil {
		t.Fatalf("go build %s did not finish within the timeout: %v", dir, ctx.Err())
	}
	return string(out), err
}

func classifyFixture(t *testing.T, goBin, dir string, want *regexp.Regexp) (compileVerdict, string) {
	t.Helper()
	out, err := buildFixture(t, goBin, dir)
	switch {
	case err == nil:
		return verdictCompiled, out
	case want.MatchString(out):
		return verdictExpected, out
	default:
		var exitErr *exec.ExitError
		if !errors.As(err, &exitErr) {
			t.Fatalf("could not run the compiler on %s: %v\n%s", dir, err, out)
		}
		return verdictWrongReason, strings.TrimSpace(out)
	}
}
